import {
  type RouteConfig,
  index,
  layout,
  route,
} from "@react-router/dev/routes";

export default [
  route("robots.txt", "routes/robots[.]txt.ts"),
  route("sitemap.xml", "routes/sitemap[.]xml.ts"),
  route("api/cms/auth/bootstrap", "routes/api.cms.auth.bootstrap.ts"),
  route("api/cms/auth/login", "routes/api.cms.auth.login.ts"),
  route("api/cms/auth/logout", "routes/api.cms.auth.logout.ts"),
  route("api/cms/auth/me", "routes/api.cms.auth.me.ts"),
  route("api/cms/content", "routes/api.cms.content.ts"),
  route("api/cms/content/:key", "routes/api.cms.content.$key.ts"),
  route("api/cms/media", "routes/api.cms.media.ts"),
  route("api/cms/media/:id", "routes/api.cms.media.$id.ts"),
  route("api/cms/media/:id/file", "routes/api.cms.media.$id.file.ts"),
  route("admin/login", "routes/admin.login.tsx"),
  route("admin/setup", "routes/admin.setup.tsx"),
  route("admin", "routes/admin.tsx", [
    index("routes/admin._index.tsx"),
    route("logout", "routes/admin.logout.tsx"),
    route("drafts", "routes/admin.drafts.tsx"),
    route("products/new", "routes/admin.products.new.tsx"),
    route("products/:key", "routes/admin.products.$key.tsx"),
    route("products", "routes/admin.products.tsx"),
    route("news/new", "routes/admin.news.new.tsx"),
    route("news/:key", "routes/admin.news.$key.tsx"),
    route("news", "routes/admin.news.tsx"),
    route("certificates/new", "routes/admin.certificates.new.tsx"),
    route("certificates/:key", "routes/admin.certificates.$key.tsx"),
    route("certificates", "routes/admin.certificates.tsx"),
    route("catalogs/new", "routes/admin.catalogs.new.tsx"),
    route("catalogs/:key", "routes/admin.catalogs.$key.tsx"),
    route("catalogs", "routes/admin.catalogs.tsx"),
    route("media", "routes/admin.media.tsx"),
    route("settings", "routes/admin.settings.tsx"),
    route("users", "routes/admin.users.tsx"),
  ]),
  layout("routes/_layout.tsx", [
    index("routes/locale-redirect.tsx"),
    route(":locale", "routes/_locale.tsx", [
      index("routes/home.tsx"),
      route("about", "routes/about.tsx"),
      route("services", "routes/services.tsx"),
      route("products", "routes/products.tsx"),
      route("products/:slug", "routes/products.$slug.tsx"),
      route("catalogs", "routes/catalogs.tsx"),
      route("news", "routes/news.tsx"),
      route("news/:slug", "routes/news.$slug.tsx"),
      route("careers", "routes/careers.tsx"),
      route("careers/:slug", "routes/careers.$slug.tsx"),
      route("contact", "routes/contact.tsx"),
      route("*", "routes/$.tsx"),
    ]),
  ]),
] satisfies RouteConfig;
